apiVersion: v1
data:
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - PodTemplate
      clusters:
      - https://10.197.96.161:6443
  resource.inclusions: |
    - apiGroups:
      - "run.tanzu.vmware.com"
      kinds:
      - TanzuKubernetesAddon
      - TanzuKubernetesCluster
      - TanzuKubernetesRelease
      - TkgServiceConfiguration
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "cluster.x-k8s.io"
      kinds:
      - Cluster
      - Machine
      - MachineDeployment
      - MachineHealthCheck
      - MachineSet
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "vmoperator.vmware.com"
      kinds:
      - ClusterVirtualMachineImage
      - VirtualMachine
      - VirtualMachineClass
      - VirtualMachineImage
      - VirtualMachinePublishRequest
      - VirtualMachineService
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "controlplane.cluster.x-k8s.io"
      - "bootstrap.cluster.x-k8s.io"
      kinds:
      - KubeadmControlPlane
      - KubeadmConfig
      - KubeadmConfigTemplate
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "infrastructure.cluster.vmware.com"
      kinds:
      - "*"
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "rbac.authorization.k8s.io"
      kinds:
      - Role
      - RoleBinding
      clusters:
      - https://10.197.96.161:6443
    - apiGroups:
      - "*"
      kinds:
      - ConfigMap
      - Secret
      clusters:
      - https://10.197.96.161:6443
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
