apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-vm
  namespace: argocd
spec:
  destination:
    namespace: tools
    server: https://10.197.96.161:6443
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  source:
    path: vmservice
    repoURL: https://github.com/beyondelastic/gitops-tkgs
    targetRevision: HEAD
