apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-app
  namespace: argocd
spec:
  destination:
    server: https://10.197.116.129:6443
  project: default
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
  source:
    path: tkg-config 
    repoURL: https://github.com/beyondelastic/gitops-tkgs.git
    targetRevision: HEAD
