apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-app
  namespace: argocd
spec:
  destination:
    server: 10.197.116.129
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  source:
    path: 
    repoURL: https://github.com/beyondelastic/gitops-tkgs.git
    targetRevision: HEAD
